# **Homework**

In [17]:
import pandas as pd
pd.__version__

'1.5.1'

In [18]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-17 17:37:22--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv.1’

housing.csv.1       100%[===================>]   1.36M  --.-KB/s    in 0.009s

2023-09-17 17:37:22 (152 MB/s) - ‘housing.csv.1’ saved [1423529/1423529]

In [19]:
import pandas as pd

# Read the housing.csv file
housing_df = pd.read_csv('housing.csv')

# Print the number of columns
num_columns = len(housing_df.columns)
print('Number of columns:', num_columns)

Number of columns: 10

In [20]:
housing_df.head()

   longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

In [6]:
missing_values = housing_df.isnull().sum()
print(missing_values)

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [8]:
housing_df.describe(include="all")

           longitude      latitude  ...  median_house_value  ocean_proximity
count   20640.000000  20640.000000  ...        20640.000000            20640
unique           NaN           NaN  ...                 NaN                5
top              NaN           NaN  ...                 NaN        <1H OCEAN
freq             NaN           NaN  ...                 NaN             9136
mean     -119.569704     35.631861  ...       206855.816909              NaN
std         2.003532      2.135952  ...       115395.615874              NaN
min      -124.350000     32.540000  ...        14999.000000              NaN
25%      -121.800000     33.930000  ...       119600.000000              NaN
50%      -118.490000     34.260000  ...       179700.000000              NaN
75%      -118.010000     37.710000  ...       264725.000000              NaN
max      -114.310000     41.950000  ...       500001.000000              NaN

[11 rows x 10 columns]

5 unique ocean_proximity

In [11]:
# Calculate the average value of the median_house_value for houses located near the bay

average_value = housing_df[housing_df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

average_value

259212.31179039303

In [12]:
mean_total_bedrooms = housing_df['total_bedrooms'].mean()

housing_df['total_bedrooms'].fillna(mean_total_bedrooms, inplace=True)

new_mean_total_bedrooms = housing_df['total_bedrooms'].mean()

new_mean_total_bedrooms

537.8705525375617

In [14]:
mean_total_bedrooms

537.8705525375618

there is no big difference in the mean value. as the mean doesnt include the missing values in the calculation

In [16]:
import numpy as np
# Select options located on islands and specific columns
island_df = housing_df[housing_df['ocean_proximity'] == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']]

# Get the underlying NumPy array
X = island_df.values

# Compute matrix-matrix multiplication between the transpose of X and X
XTX = X.T.dot(X)

# Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)

# Create array y
y = np.array([950, 1300, 800, 1000, 1300])

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y
w = XTX_inv.dot(X.T).dot(y)

# Get the value of the last element of w
last_element_w = w[-1]

last_element_w

5.699229455065586